### ISSUE TITLE
sth got woring

### ISSUE THREAD

**Issue by Yo-yo-ooo** [marceldobehere/MaslOS-2#1]
<img width="411" alt="image" src="https://github.com/marceldobehere/MaslOS-2/assets/98507772/a1f56491-b53a-40d0-b993-cbbd5c4e6105">

**Comment by Yo-yo-ooo** [comment]
Fault There
<img width="414" alt="image" src="https://github.com/marceldobehere/MaslOS-2/assets/98507772/a24363b3-4b86-497c-ab59-2d4373790093">

**Comment by marceldobehere** [comment]
This is actually intended.
There is a test program in running userspace and in kernel space. It should make the screen flicker blue in kernel space and the user space program should "crash" with a page fault (interrupt 14)

This is currently intended bc I just finished making userspace work and its there for testing rn
